server {
    listen 80;
    # Regex estricta para evitar LFI (Path Traversal). Solo acepta subdirectorios alfanuméricos válidos.
    server_name ~^(www\.)?(?<domain>[a-zA-Z0-9\-\.]+\.com\.ar)$;
    
    root /usr/share/nginx/html/$domain;
    index index.html;

    # Headers de seguridad
    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Content-Type-Options "nosniff";

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Desactivar logs de acceso para rendimiento y privacidad PBN
    access_log off;
    error_log /var/log/nginx/pbn_error.log warn;
}
