// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/admin/administracion/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/administracion">> = Specific
  const handler = {} as typeof import("../../src/app/admin/administracion/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/caja/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/caja">> = Specific
  const handler = {} as typeof import("../../src/app/admin/caja/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/calibrador/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/calibrador">> = Specific
  const handler = {} as typeof import("../../src/app/admin/calibrador/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/configuracion/laboratorios/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/configuracion/laboratorios">> = Specific
  const handler = {} as typeof import("../../src/app/admin/configuracion/laboratorios/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/configuracion/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/configuracion">> = Specific
  const handler = {} as typeof import("../../src/app/admin/configuracion/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/contactos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/contactos">> = Specific
  const handler = {} as typeof import("../../src/app/admin/contactos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/cotizador/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/cotizador">> = Specific
  const handler = {} as typeof import("../../src/app/admin/cotizador/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/desarrollo/campanas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/desarrollo/campanas">> = Specific
  const handler = {} as typeof import("../../src/app/admin/desarrollo/campanas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/desarrollo/carritos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/desarrollo/carritos">> = Specific
  const handler = {} as typeof import("../../src/app/admin/desarrollo/carritos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/desarrollo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/desarrollo">> = Specific
  const handler = {} as typeof import("../../src/app/admin/desarrollo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/desarrollo/postventa/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/desarrollo/postventa">> = Specific
  const handler = {} as typeof import("../../src/app/admin/desarrollo/postventa/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/desarrollo/social/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/desarrollo/social">> = Specific
  const handler = {} as typeof import("../../src/app/admin/desarrollo/social/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/equipo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/equipo">> = Specific
  const handler = {} as typeof import("../../src/app/admin/equipo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/facturacion/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/facturacion">> = Specific
  const handler = {} as typeof import("../../src/app/admin/facturacion/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/gastos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/gastos">> = Specific
  const handler = {} as typeof import("../../src/app/admin/gastos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/inventario/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/inventario">> = Specific
  const handler = {} as typeof import("../../src/app/admin/inventario/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/leads/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/leads">> = Specific
  const handler = {} as typeof import("../../src/app/admin/leads/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/pedidos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/pedidos">> = Specific
  const handler = {} as typeof import("../../src/app/admin/pedidos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/reportes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/reportes">> = Specific
  const handler = {} as typeof import("../../src/app/admin/reportes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/smartlab-bookmarklet/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/smartlab-bookmarklet">> = Specific
  const handler = {} as typeof import("../../src/app/admin/smartlab-bookmarklet/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/ventas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/ventas">> = Specific
  const handler = {} as typeof import("../../src/app/admin/ventas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/web/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/web">> = Specific
  const handler = {} as typeof import("../../src/app/admin/web/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/whatsapp/fotos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/whatsapp/fotos">> = Specific
  const handler = {} as typeof import("../../src/app/admin/whatsapp/fotos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/whatsapp/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/whatsapp">> = Specific
  const handler = {} as typeof import("../../src/app/admin/whatsapp/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/arma-tus-lentes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/arma-tus-lentes">> = Specific
  const handler = {} as typeof import("../../src/app/arma-tus-lentes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/blog/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/blog/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/blog/busquedas/[query]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/busquedas/[query]">> = Specific
  const handler = {} as typeof import("../../src/app/blog/busquedas/[query]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/blog/colores-cristales/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/colores-cristales">> = Specific
  const handler = {} as typeof import("../../src/app/blog/colores-cristales/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/blog/como-leer-receta-oftalmologica/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/como-leer-receta-oftalmologica">> = Specific
  const handler = {} as typeof import("../../src/app/blog/como-leer-receta-oftalmologica/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/blog/como-limpiar-anteojos-sin-rayar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/como-limpiar-anteojos-sin-rayar">> = Specific
  const handler = {} as typeof import("../../src/app/blog/como-limpiar-anteojos-sin-rayar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/blog/control-miopia-infantil-lentes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/control-miopia-infantil-lentes">> = Specific
  const handler = {} as typeof import("../../src/app/blog/control-miopia-infantil-lentes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/blog/control-miopia/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/control-miopia">> = Specific
  const handler = {} as typeof import("../../src/app/blog/control-miopia/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/blog/diferencia-miopia-hipermetropia-astigmatismo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/diferencia-miopia-hipermetropia-astigmatismo">> = Specific
  const handler = {} as typeof import("../../src/app/blog/diferencia-miopia-hipermetropia-astigmatismo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/blog/faq/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/faq">> = Specific
  const handler = {} as typeof import("../../src/app/blog/faq/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/blog/filtro-azul-vs-antirreflejo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/filtro-azul-vs-antirreflejo">> = Specific
  const handler = {} as typeof import("../../src/app/blog/filtro-azul-vs-antirreflejo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/blog/guia-armazones-segun-rostro/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/guia-armazones-segun-rostro">> = Specific
  const handler = {} as typeof import("../../src/app/blog/guia-armazones-segun-rostro/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/blog/guia-cristales/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/guia-cristales">> = Specific
  const handler = {} as typeof import("../../src/app/blog/guia-cristales/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/blog/guia-precios-multifocales-argentina/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/guia-precios-multifocales-argentina">> = Specific
  const handler = {} as typeof import("../../src/app/blog/guia-precios-multifocales-argentina/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/blog/lentes-fotocromaticos-transitions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/lentes-fotocromaticos-transitions">> = Specific
  const handler = {} as typeof import("../../src/app/blog/lentes-fotocromaticos-transitions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/blog/lentes-polarizados-vs-comunes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/lentes-polarizados-vs-comunes">> = Specific
  const handler = {} as typeof import("../../src/app/blog/lentes-polarizados-vs-comunes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/blog/materiales-armazones-acetato-tr90/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/materiales-armazones-acetato-tr90">> = Specific
  const handler = {} as typeof import("../../src/app/blog/materiales-armazones-acetato-tr90/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/blog/matias-turchi/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/matias-turchi">> = Specific
  const handler = {} as typeof import("../../src/app/blog/matias-turchi/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/blog/mitos-lentes-contacto/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/mitos-lentes-contacto">> = Specific
  const handler = {} as typeof import("../../src/app/blog/mitos-lentes-contacto/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/blog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog">> = Specific
  const handler = {} as typeof import("../../src/app/blog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/blog/peligros-anteojos-pregraduados-farmacia/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/peligros-anteojos-pregraduados-farmacia">> = Specific
  const handler = {} as typeof import("../../src/app/blog/peligros-anteojos-pregraduados-farmacia/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/blog/por-que-no-pegar-anteojos-la-gotita/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/por-que-no-pegar-anteojos-la-gotita">> = Specific
  const handler = {} as typeof import("../../src/app/blog/por-que-no-pegar-anteojos-la-gotita/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/blog/sintomas-presbicia-soluciones/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/sintomas-presbicia-soluciones">> = Specific
  const handler = {} as typeof import("../../src/app/blog/sintomas-presbicia-soluciones/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/blog/varilux-vs-kodak-vs-zeiss/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/varilux-vs-kodak-vs-zeiss">> = Specific
  const handler = {} as typeof import("../../src/app/blog/varilux-vs-kodak-vs-zeiss/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/checkout/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/checkout">> = Specific
  const handler = {} as typeof import("../../src/app/checkout/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/clip-on/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/clip-on">> = Specific
  const handler = {} as typeof import("../../src/app/clip-on/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/como-comprar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/como-comprar">> = Specific
  const handler = {} as typeof import("../../src/app/como-comprar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/contacto/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contacto">> = Specific
  const handler = {} as typeof import("../../src/app/contacto/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/cristales-opticos/blue-uv/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cristales-opticos/blue-uv">> = Specific
  const handler = {} as typeof import("../../src/app/cristales-opticos/blue-uv/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/cristales-opticos/crizal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cristales-opticos/crizal">> = Specific
  const handler = {} as typeof import("../../src/app/cristales-opticos/crizal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/cristales-opticos/kodak/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cristales-opticos/kodak">> = Specific
  const handler = {} as typeof import("../../src/app/cristales-opticos/kodak/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/cristales-opticos/myofix/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cristales-opticos/myofix">> = Specific
  const handler = {} as typeof import("../../src/app/cristales-opticos/myofix/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/cristales-opticos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cristales-opticos">> = Specific
  const handler = {} as typeof import("../../src/app/cristales-opticos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/cristales-opticos/stellest/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cristales-opticos/stellest">> = Specific
  const handler = {} as typeof import("../../src/app/cristales-opticos/stellest/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/cristales-opticos/transitions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cristales-opticos/transitions">> = Specific
  const handler = {} as typeof import("../../src/app/cristales-opticos/transitions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/cristales-opticos/varilux/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cristales-opticos/varilux">> = Specific
  const handler = {} as typeof import("../../src/app/cristales-opticos/varilux/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/cristales-opticos/xperio/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cristales-opticos/xperio">> = Specific
  const handler = {} as typeof import("../../src/app/cristales-opticos/xperio/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/faq/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/faq">> = Specific
  const handler = {} as typeof import("../../src/app/faq/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/landing/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/landing/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/landing/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/landing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/landing">> = Specific
  const handler = {} as typeof import("../../src/app/landing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/landing/wicue/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/landing/wicue">> = Specific
  const handler = {} as typeof import("../../src/app/landing/wicue/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/lentes-de-contacto/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lentes-de-contacto">> = Specific
  const handler = {} as typeof import("../../src/app/lentes-de-contacto/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/lentes-de-sol/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lentes-de-sol">> = Specific
  const handler = {} as typeof import("../../src/app/lentes-de-sol/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/nuestro-local/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/nuestro-local">> = Specific
  const handler = {} as typeof import("../../src/app/nuestro-local/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/obras-sociales/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/obras-sociales">> = Specific
  const handler = {} as typeof import("../../src/app/obras-sociales/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/politicas-de-cambio/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/politicas-de-cambio">> = Specific
  const handler = {} as typeof import("../../src/app/politicas-de-cambio/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/politicas-de-privacidad/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/politicas-de-privacidad">> = Specific
  const handler = {} as typeof import("../../src/app/politicas-de-privacidad/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/producto/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/producto/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/producto/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/promo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/promo">> = Specific
  const handler = {} as typeof import("../../src/app/promo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/quienes-somos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/quienes-somos">> = Specific
  const handler = {} as typeof import("../../src/app/quienes-somos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/receta/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/receta">> = Specific
  const handler = {} as typeof import("../../src/app/receta/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/resenas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/resenas">> = Specific
  const handler = {} as typeof import("../../src/app/resenas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/terminos-y-condiciones/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terminos-y-condiciones">> = Specific
  const handler = {} as typeof import("../../src/app/terminos-y-condiciones/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/tienda/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tienda">> = Specific
  const handler = {} as typeof import("../../src/app/tienda/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/urgencias/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/urgencias">> = Specific
  const handler = {} as typeof import("../../src/app/urgencias/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/alert/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/alert">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/alert/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/blog/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/blog/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/blog/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/blog/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/blog">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/blog/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/coupons/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/coupons/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/coupons/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/coupons/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/coupons">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/coupons/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/fix-names/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/fix-names">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/fix-names/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/fix-phones/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/fix-phones">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/fix-phones/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/web-products/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/web-products">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/web-products/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/agents/chat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agents/chat">> = Specific
  const handler = {} as typeof import("../../src/app/api/agents/chat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/agents/seo/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agents/seo">> = Specific
  const handler = {} as typeof import("../../src/app/api/agents/seo/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ai/process-image/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/process-image">> = Specific
  const handler = {} as typeof import("../../src/app/api/ai/process-image/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/login">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/logout">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/me/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/me">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/me/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/backup/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/backup">> = Specific
  const handler = {} as typeof import("../../src/app/api/backup/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/backup/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/backup/status">> = Specific
  const handler = {} as typeof import("../../src/app/api/backup/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/billing/config/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing/config">> = Specific
  const handler = {} as typeof import("../../src/app/api/billing/config/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/billing/invoice/[id]/pdf-data/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing/invoice/[id]/pdf-data">> = Specific
  const handler = {} as typeof import("../../src/app/api/billing/invoice/[id]/pdf-data/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/billing/invoice/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing/invoice/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/billing/invoice/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/billing/invoice/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing/invoice">> = Specific
  const handler = {} as typeof import("../../src/app/api/billing/invoice/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/blog/generate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/blog/generate">> = Specific
  const handler = {} as typeof import("../../src/app/api/blog/generate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/blog/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/blog">> = Specific
  const handler = {} as typeof import("../../src/app/api/blog/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/bot/clients/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bot/clients">> = Specific
  const handler = {} as typeof import("../../src/app/api/bot/clients/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/bot/hitos/extract/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bot/hitos/extract">> = Specific
  const handler = {} as typeof import("../../src/app/api/bot/hitos/extract/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/bot/interactions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bot/interactions">> = Specific
  const handler = {} as typeof import("../../src/app/api/bot/interactions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/bot/messages/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bot/messages">> = Specific
  const handler = {} as typeof import("../../src/app/api/bot/messages/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/bot/notify-invoice/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bot/notify-invoice">> = Specific
  const handler = {} as typeof import("../../src/app/api/bot/notify-invoice/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/bot/orders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bot/orders">> = Specific
  const handler = {} as typeof import("../../src/app/api/bot/orders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/bot/prescriptions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bot/prescriptions">> = Specific
  const handler = {} as typeof import("../../src/app/api/bot/prescriptions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/bot/pricing/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bot/pricing">> = Specific
  const handler = {} as typeof import("../../src/app/api/bot/pricing/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/bot/products/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bot/products">> = Specific
  const handler = {} as typeof import("../../src/app/api/bot/products/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/bot/tasks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bot/tasks">> = Specific
  const handler = {} as typeof import("../../src/app/api/bot/tasks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cash/movement/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cash/movement">> = Specific
  const handler = {} as typeof import("../../src/app/api/cash/movement/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cash/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cash">> = Specific
  const handler = {} as typeof import("../../src/app/api/cash/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/catalog/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/catalog">> = Specific
  const handler = {} as typeof import("../../src/app/api/catalog/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/checkout/config/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/checkout/config">> = Specific
  const handler = {} as typeof import("../../src/app/api/checkout/config/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/checkout/payway/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/checkout/payway">> = Specific
  const handler = {} as typeof import("../../src/app/api/checkout/payway/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/checkout/recovery-email/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/checkout/recovery-email">> = Specific
  const handler = {} as typeof import("../../src/app/api/checkout/recovery-email/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/checkout/session/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/checkout/session">> = Specific
  const handler = {} as typeof import("../../src/app/api/checkout/session/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/checkout/validate-coupon/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/checkout/validate-coupon">> = Specific
  const handler = {} as typeof import("../../src/app/api/checkout/validate-coupon/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/complaints/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/complaints">> = Specific
  const handler = {} as typeof import("../../src/app/api/complaints/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/contacts/[id]/can-close/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contacts/[id]/can-close">> = Specific
  const handler = {} as typeof import("../../src/app/api/contacts/[id]/can-close/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/contacts/[id]/favorite/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contacts/[id]/favorite">> = Specific
  const handler = {} as typeof import("../../src/app/api/contacts/[id]/favorite/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/contacts/[id]/interactions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contacts/[id]/interactions">> = Specific
  const handler = {} as typeof import("../../src/app/api/contacts/[id]/interactions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/contacts/[id]/payments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contacts/[id]/payments">> = Specific
  const handler = {} as typeof import("../../src/app/api/contacts/[id]/payments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/contacts/[id]/prescriptions/[presId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contacts/[id]/prescriptions/[presId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/contacts/[id]/prescriptions/[presId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/contacts/[id]/prescriptions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contacts/[id]/prescriptions">> = Specific
  const handler = {} as typeof import("../../src/app/api/contacts/[id]/prescriptions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/contacts/[id]/priority/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contacts/[id]/priority">> = Specific
  const handler = {} as typeof import("../../src/app/api/contacts/[id]/priority/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/contacts/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contacts/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/contacts/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/contacts/[id]/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contacts/[id]/status">> = Specific
  const handler = {} as typeof import("../../src/app/api/contacts/[id]/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/contacts/[id]/tasks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contacts/[id]/tasks">> = Specific
  const handler = {} as typeof import("../../src/app/api/contacts/[id]/tasks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/contacts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contacts">> = Specific
  const handler = {} as typeof import("../../src/app/api/contacts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/copilot/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/copilot">> = Specific
  const handler = {} as typeof import("../../src/app/api/copilot/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/abandoned-carts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/abandoned-carts">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/abandoned-carts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/auto-blog/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/auto-blog">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/auto-blog/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/daily-cash/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/daily-cash">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/daily-cash/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/followups/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/followups">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/followups/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/kazwini-sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/kazwini-sync">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/kazwini-sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/overdue-balances/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/overdue-balances">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/overdue-balances/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/payment-report/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/payment-report">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/payment-report/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/pickup-reminder/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/pickup-reminder">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/pickup-reminder/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/smartlab-sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/smartlab-sync">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/smartlab-sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/crystal-colors/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/crystal-colors/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/crystal-colors/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/crystal-colors/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/crystal-colors">> = Specific
  const handler = {} as typeof import("../../src/app/api/crystal-colors/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dashboard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/api/dashboard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/diag/afip/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/diag/afip">> = Specific
  const handler = {} as typeof import("../../src/app/api/diag/afip/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/diag/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/diag">> = Specific
  const handler = {} as typeof import("../../src/app/api/diag/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/doctors/commissions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/doctors/commissions">> = Specific
  const handler = {} as typeof import("../../src/app/api/doctors/commissions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/doctors/payments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/doctors/payments">> = Specific
  const handler = {} as typeof import("../../src/app/api/doctors/payments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/doctors/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/doctors">> = Specific
  const handler = {} as typeof import("../../src/app/api/doctors/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/email/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/email">> = Specific
  const handler = {} as typeof import("../../src/app/api/email/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/equipo/mensajes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/equipo/mensajes">> = Specific
  const handler = {} as typeof import("../../src/app/api/equipo/mensajes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/expenses/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/expenses">> = Specific
  const handler = {} as typeof import("../../src/app/api/expenses/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/export">> = Specific
  const handler = {} as typeof import("../../src/app/api/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/fixed-costs/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/fixed-costs/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/fixed-costs/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/fixed-costs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/fixed-costs">> = Specific
  const handler = {} as typeof import("../../src/app/api/fixed-costs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/lab-ready/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/lab-ready">> = Specific
  const handler = {} as typeof import("../../src/app/api/lab-ready/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/laboratories/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/laboratories/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/laboratories/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/laboratories/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/laboratories">> = Specific
  const handler = {} as typeof import("../../src/app/api/laboratories/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/leads/pipeline/move/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leads/pipeline/move">> = Specific
  const handler = {} as typeof import("../../src/app/api/leads/pipeline/move/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/leads/pipeline/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leads/pipeline">> = Specific
  const handler = {} as typeof import("../../src/app/api/leads/pipeline/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/marketing/dashboard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/marketing/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/api/marketing/dashboard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/notifications/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/notifications/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/notifications/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications">> = Specific
  const handler = {} as typeof import("../../src/app/api/notifications/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ocr/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ocr">> = Specific
  const handler = {} as typeof import("../../src/app/api/ocr/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/orders/[id]/confirm-web/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders/[id]/confirm-web">> = Specific
  const handler = {} as typeof import("../../src/app/api/orders/[id]/confirm-web/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/orders/[id]/notify-ready/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders/[id]/notify-ready">> = Specific
  const handler = {} as typeof import("../../src/app/api/orders/[id]/notify-ready/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/orders/[id]/payments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders/[id]/payments">> = Specific
  const handler = {} as typeof import("../../src/app/api/orders/[id]/payments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/orders/[id]/pdf/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders/[id]/pdf">> = Specific
  const handler = {} as typeof import("../../src/app/api/orders/[id]/pdf/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/orders/[id]/refresh-prices/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders/[id]/refresh-prices">> = Specific
  const handler = {} as typeof import("../../src/app/api/orders/[id]/refresh-prices/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/orders/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/orders/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/orders/[id]/send-pdf/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders/[id]/send-pdf">> = Specific
  const handler = {} as typeof import("../../src/app/api/orders/[id]/send-pdf/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/orders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders">> = Specific
  const handler = {} as typeof import("../../src/app/api/orders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/orders/web-pending-count/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders/web-pending-count">> = Specific
  const handler = {} as typeof import("../../src/app/api/orders/web-pending-count/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/orders/with-balance/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders/with-balance">> = Specific
  const handler = {} as typeof import("../../src/app/api/orders/with-balance/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/payments/[id]/receipt-pdf/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payments/[id]/receipt-pdf">> = Specific
  const handler = {} as typeof import("../../src/app/api/payments/[id]/receipt-pdf/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/payments/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payments/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/payments/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/payments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payments">> = Specific
  const handler = {} as typeof import("../../src/app/api/payments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/products/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/products/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/products/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/products/bulk/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/products/bulk">> = Specific
  const handler = {} as typeof import("../../src/app/api/products/bulk/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/products/delete-all/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/products/delete-all">> = Specific
  const handler = {} as typeof import("../../src/app/api/products/delete-all/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/products/fix-categories/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/products/fix-categories">> = Specific
  const handler = {} as typeof import("../../src/app/api/products/fix-categories/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/products/import/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/products/import">> = Specific
  const handler = {} as typeof import("../../src/app/api/products/import/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/products/ocr-update/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/products/ocr-update">> = Specific
  const handler = {} as typeof import("../../src/app/api/products/ocr-update/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/products/recalculate-stock/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/products/recalculate-stock">> = Specific
  const handler = {} as typeof import("../../src/app/api/products/recalculate-stock/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/products/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/products">> = Specific
  const handler = {} as typeof import("../../src/app/api/products/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/reports/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reports">> = Specific
  const handler = {} as typeof import("../../src/app/api/reports/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/review-requests/pending/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/review-requests/pending">> = Specific
  const handler = {} as typeof import("../../src/app/api/review-requests/pending/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/reviews/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reviews">> = Specific
  const handler = {} as typeof import("../../src/app/api/reviews/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/sales-opportunities/generate-message/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sales-opportunities/generate-message">> = Specific
  const handler = {} as typeof import("../../src/app/api/sales-opportunities/generate-message/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/sales-opportunities/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sales-opportunities">> = Specific
  const handler = {} as typeof import("../../src/app/api/sales-opportunities/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/search">> = Specific
  const handler = {} as typeof import("../../src/app/api/search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/seo/generate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/seo/generate">> = Specific
  const handler = {} as typeof import("../../src/app/api/seo/generate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/service-pricing/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/service-pricing/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/service-pricing/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/service-pricing/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/service-pricing">> = Specific
  const handler = {} as typeof import("../../src/app/api/service-pricing/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/settings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings">> = Specific
  const handler = {} as typeof import("../../src/app/api/settings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/smartlab-submit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/smartlab-submit">> = Specific
  const handler = {} as typeof import("../../src/app/api/smartlab-submit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/smartlab-sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/smartlab-sync">> = Specific
  const handler = {} as typeof import("../../src/app/api/smartlab-sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/social/generate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/social/generate">> = Specific
  const handler = {} as typeof import("../../src/app/api/social/generate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/social/history/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/social/history">> = Specific
  const handler = {} as typeof import("../../src/app/api/social/history/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/storage/local-upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/storage/local-upload">> = Specific
  const handler = {} as typeof import("../../src/app/api/storage/local-upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/storage/upload-url/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/storage/upload-url">> = Specific
  const handler = {} as typeof import("../../src/app/api/storage/upload-url/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/storage/view/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/storage/view">> = Specific
  const handler = {} as typeof import("../../src/app/api/storage/view/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/store/products/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/store/products">> = Specific
  const handler = {} as typeof import("../../src/app/api/store/products/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tags/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tags/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/tags/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tags/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tags">> = Specific
  const handler = {} as typeof import("../../src/app/api/tags/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/targets/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/targets">> = Specific
  const handler = {} as typeof import("../../src/app/api/targets/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tasks/pending/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tasks/pending">> = Specific
  const handler = {} as typeof import("../../src/app/api/tasks/pending/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/upload">> = Specific
  const handler = {} as typeof import("../../src/app/api/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/users/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/users/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users">> = Specific
  const handler = {} as typeof import("../../src/app/api/users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/web/checkout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/web/checkout">> = Specific
  const handler = {} as typeof import("../../src/app/api/web/checkout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/web/contacto/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/web/contacto">> = Specific
  const handler = {} as typeof import("../../src/app/api/web/contacto/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/web/pricing/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/web/pricing">> = Specific
  const handler = {} as typeof import("../../src/app/api/web/pricing/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/web/temp-debug/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/web/temp-debug">> = Specific
  const handler = {} as typeof import("../../src/app/api/web/temp-debug/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/whatsapp/agent/catalog/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/whatsapp/agent/catalog">> = Specific
  const handler = {} as typeof import("../../src/app/api/whatsapp/agent/catalog/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/whatsapp/agent/media/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/whatsapp/agent/media">> = Specific
  const handler = {} as typeof import("../../src/app/api/whatsapp/agent/media/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/whatsapp/agent/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/whatsapp/agent">> = Specific
  const handler = {} as typeof import("../../src/app/api/whatsapp/agent/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/whatsapp/chats/[id]/bot/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/whatsapp/chats/[id]/bot">> = Specific
  const handler = {} as typeof import("../../src/app/api/whatsapp/chats/[id]/bot/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/whatsapp/chats/[id]/extract-client/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/whatsapp/chats/[id]/extract-client">> = Specific
  const handler = {} as typeof import("../../src/app/api/whatsapp/chats/[id]/extract-client/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/whatsapp/chats/[id]/mark-read/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/whatsapp/chats/[id]/mark-read">> = Specific
  const handler = {} as typeof import("../../src/app/api/whatsapp/chats/[id]/mark-read/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/whatsapp/chats/[id]/messages/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/whatsapp/chats/[id]/messages">> = Specific
  const handler = {} as typeof import("../../src/app/api/whatsapp/chats/[id]/messages/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/whatsapp/chats/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/whatsapp/chats/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/whatsapp/chats/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/whatsapp/chats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/whatsapp/chats">> = Specific
  const handler = {} as typeof import("../../src/app/api/whatsapp/chats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/whatsapp/chats/unread-count/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/whatsapp/chats/unread-count">> = Specific
  const handler = {} as typeof import("../../src/app/api/whatsapp/chats/unread-count/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/whatsapp/notify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/whatsapp/notify">> = Specific
  const handler = {} as typeof import("../../src/app/api/whatsapp/notify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/whatsapp/send/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/whatsapp/send">> = Specific
  const handler = {} as typeof import("../../src/app/api/whatsapp/send/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/whatsapp/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/whatsapp/status">> = Specific
  const handler = {} as typeof import("../../src/app/api/whatsapp/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/whatsapp/sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/whatsapp/sync">> = Specific
  const handler = {} as typeof import("../../src/app/api/whatsapp/sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/whatsapp/test-chat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/whatsapp/test-chat">> = Specific
  const handler = {} as typeof import("../../src/app/api/whatsapp/test-chat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/contacto/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/contacto">> = Specific
  const handler = {} as typeof import("../../src/app/contacto/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/cristales-opticos/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/cristales-opticos">> = Specific
  const handler = {} as typeof import("../../src/app/cristales-opticos/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/faq/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/faq">> = Specific
  const handler = {} as typeof import("../../src/app/faq/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/tienda/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/tienda">> = Specific
  const handler = {} as typeof import("../../src/app/tienda/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
