-- AlterTable
ALTER TABLE "Prescription" ADD COLUMN IF NOT EXISTS "nearDistanceOD" DOUBLE PRECISION;
ALTER TABLE "Prescription" ADD COLUMN IF NOT EXISTS "nearDistanceOI" DOUBLE PRECISION;
ALTER TABLE "Prescription" ADD COLUMN IF NOT EXISTS "nearPd" DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "labType" TEXT;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "origin" TEXT;

-- AlterTable
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "labEdgeInStore" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "labHeightOD" DOUBLE PRECISION;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "labHeightOI" DOUBLE PRECISION;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "labMaterial" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "labNearPdOd" DOUBLE PRECISION;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "labNearPdOi" DOUBLE PRECISION;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "labType" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "smartLabDetails" TEXT;

ALTER TABLE "Order" ALTER COLUMN "labPdOd" TYPE DOUBLE PRECISION USING (NULLIF(regexp_replace("labPdOd"::text, '[^0-9.]', '', 'g'), '')::double precision);
ALTER TABLE "Order" ALTER COLUMN "labPdOi" TYPE DOUBLE PRECISION USING (NULLIF(regexp_replace("labPdOi"::text, '[^0-9.]', '', 'g'), '')::double precision);

-- AlterTable
ALTER TABLE "Invoice" ADD COLUMN IF NOT EXISTS "observations" TEXT;
