-- AlterTable
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "smartLabSector" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "smartLabProgress" INTEGER;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "smartLabLastSync" TIMESTAMP(3);
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "smartLabEntryDate" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "smartLabDays" INTEGER;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "smartLabDetails" TEXT;
